### ISSUE TITLE
useLocalMedia toggleCameraEnabled turning off audio also

### ISSUE THREAD

**Issue by bva-mike** [whereby/sdk#300]
issue:

when using `localMedia.actions.toggleCameraEnabled()` from:

```
import { useLocalMedia } from '@whereby.com/browser-sdk/react';
const { localMedia } = useLocalMedia();
```

whenever i toggle my local camera off it seems to turn off the video AND audio. However using `localMedia.actions.toggleMicrophoneEnabled()`, correctly, only toggles the audio off/on, does anyone else have this issue? 

using `"@whereby.com/browser-sdk": "^3.2.2"`

any pointers to help debug this would also be great, thanks!

**Comment by thyal** [comment]
Hey 👋 

I've not been able to reproduce this on my side. It seems to correctly only toggle camera for me. Can you show the full code example, please?
