### ISSUE TITLE
 ERROR  Error: URLSearchParams.set is not implemented 

### ISSUE THREAD

**Issue by Riaz101325** [whereby/sdk#449]
this error not resolve this why

**Comment by thyal** [comment]
Hi @Riaz101325, Could you please provide some more information on the issue you are seeing?

**Comment by Riaz101325** [comment]
import React, {useRef, useEffect, useState} from 'react'
import {View, StyleSheet, Platform, PermissionsAndroid, Alert} from 'react-native'
import {heightPercentageToDP as hp, widthPercentageToDP as wp} from 'react-native-responsive-screen'
import { WherebyEmbed, type WherebyWebView, WherebyEvent } from "@whereby.com/react-native-sdk/embed";
import {useSelector} from 'react-redux'

import * as Colors from '../../../constants/colors'
import * as Typography from '../../../constants/typography'

const VedioScreen = ({route, navigation}) => {
    const {userData} = useSelector((state) => state.user)
    const lng = useSelector((state) => state.user.selectedLangauge)
    const ROOM_URL = route?.params?.roomUrl ? route?.params?.roomUrl : ''
    const [hasPermissionForAndroid, setHasPermissionForAndroid] = useState(false)
 
    const wherebyRoomRef = useRef(null)

 
    const requestAndroidPermissions = async () => {
        if (Platform.OS === 'android') {
            try {
                const granted = await PermissionsAndroid.requestMultiple([PermissionsAndroid.PERMISSIONS.CAMERA, PermissionsAndroid.PERMISSIONS.RECORD_AUDIO])
                const cameraGranted = granted[PermissionsAndroid.PERMISSIONS.CAMERA] === PermissionsAndroid.RESULTS.GRANTED
                const audioGranted = granted[PermissionsAndroid.PERMISSIONS.RECORD_AUDIO] === PermissionsAndroid.RESULTS.GRANTED

                if (!cameraGranted || !audioGranted) {
                    Alert.alert('Permissions required', 'Camera and audio permissions are required to join the meeting.')
                } else {
                    setHasPermissionForAndroid(true)
                }
            } catch (err) {
                console.warn(err)
            }
        } else {
            setHasPermissionForAndroid(true)
        }
    }

    useEffect(() => {
        requestAndroidPermissions()
    }, [])
    if (Platform.OS === 'android' && !hasPermissionForAndroid) {
        return <View />
    }

    return (
        <View style={{flex: 1}}>
        
                <View style={styles.container}>
                    <WherebyEmbed
                        ref={wherebyRoomRef}
                        room={ROOM_URL}
                        displayName={userData?.full_name} //
                        logo={false}
                        style={{flex: 1}}
                        topToolbar={false}
                        onParticipantJoin={(participant) => console.log('Participant joined', participant)}
                  
                    />
                </View>
         
        </View>
    )
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        height: '100%'
    },
    webView: {
        width: '100%',
        height: '100%'
    },
    topHeaderView: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-around',
        width: wp('100%'),
        height: hp(5),
        paddingHorizontal: wp('10%'),
        backgroundColor: '#434343'
    },
    outerTopHeaderView: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRightWidth: 1,
        borderRightColor: Colors.White,
        borderLeftWidth: 1,
        borderLeftColor: Colors.White
    },
    textCallRemain: {
        color: Colors.White,
        fontSize: Typography.FONT_SIZE_13,
        fontFamily: Typography.FONT_FAMILY_REGULAR
    },
    textCallTitle: {
        color: Colors.White,
        fontSize: Typography.FONT_SIZE_13,
        fontFamily: Typography.FONT_FAMILY_REGULAR,
        maxWidth: wp(50)
    }
})

export default VedioScreen
am use this code but show this error again and again in react native 
ERROR Error: URLSearchParams.set is not implemented 
how to resolve this issue please send me detail

**Comment by thyal** [comment]
Hey! Can you try to add this dependency? `react-native-url-polyfill` https://www.npmjs.com/package/react-native-url-polyfill. It should polyfill any uses of URL's. I will have a look at including this in the library itself, but for now this should fix your issues.

**Comment by thyal** [comment]
Closing this, as my previous comment should solve the issue, and the issue has been inactive for a while
